# Settings.yml
---
conf.py:
  project: Getting Started Tutorial
  copyright: 2004-2014
  version: 6.2.0
  release: 6.2.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted
    github_branch: latest
...
