# Settings.yml
---
conf.py:
  project: Getting Started Tutorial
  copyright: 2004-2013
  version: 1.0.1
  release: 1.0.1
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted
    github_branch: latest
...
